### ISSUE TITLE
Out of scope: "Sharing encrypted folders with whole groups" – Rationale?

### ISSUE THREAD

**Issue by kwisatz** [nextcloud/end_to_end_encryption_rfc#28]
Given the following chunk of the RFC:

> Existing client-side encryption solutions often prevent the sharing of encrypted files, the Nextcloud end-to-end encryption must offer support for the following sharing scenarios:
> 
> - Sharing encrypted folders with other users
> 
> The following sharing scenarios are considered out of-scope:
> 
> - Sharing single files or folders from an encrypted folder
> - Sharing encrypted folders with whole groups

While I understand why `Sharing single files or folders from an encrypted folder` would be complicated under the described architecture, I'm not sure I understand why sharing with while groups has been declared out of scope? 

Would someone be able to give a rationale/explain why this decision has been made? Thanks!

**Comment by tobiasKaminsky** [comment]
Groups are managed by server and as the server is not trustable in this scenario, we cannot rely on the info who is in a group.

**Comment by kwisatz** [comment]
OK, makes sense, thanks.
