### ISSUE TITLE
GCM nonce size

### ISSUE THREAD

**Issue by MaxFichtelmann** [nextcloud/end_to_end_encryption_rfc#32]
The RFC states in [uploading new files](https://github.com/nextcloud/end_to_end_encryption_rfc/blob/master/RFC.md#uploading-new-files) that the IV (Nonce) used in the GCM encryption should be of size 16 byte/128 bit.

> Generate a new 128-bit IV for the file

[RFC 5116](https://tools.ietf.org/html/rfc5116), which specifies AES/GCM describes the nonce size as 12 byte/96 bit.

**Comment by tobiasKaminsky** [comment]
Fixed in v2, which will be published soon as a draft.
