### ISSUE TITLE
Salt should not be hardcoded

### ISSUE THREAD

**Issue by rullzer** [nextcloud/end_to_end_encryption_rfc#5]
Right now all implementations hard code the salt for the password generation. We should randomly generate a salt and store it in the metadata.

**Comment by tobiasKaminsky** [comment]
I only use this for encrypt/decrypt the private key. 
But this should be independent from one single folder?

**Comment by rullzer** [comment]
The point is we should not use a hard-coded salt. Maybe this means we need to extend the api. But hard-coded salt is not the best idea.

**Comment by tobiasKaminsky** [comment]
@LukasReschke do you have an idea what we can do here?

**Comment by LukasReschke** [comment]
So is this a salt that is used for the private key before sending it to the Nextcloud server? If so, just prepend it to the private key and split that one then. Needs adjustments on all clients though.

**Comment by tobiasKaminsky** [comment]
@rullzer @marinofaggiana are you fine with this?

**Comment by rullzer** [comment]
Sure, as long as it is documented I'm fine.
But since this is more part of the app. Can't we just have another field where we store this?

**Comment by marinofaggiana** [comment]
another field on API for send and receive private key ?

**Comment by tobiasKaminsky** [comment]
Can you do this? @schiessle

**Comment by marinofaggiana** [comment]
@tobiasKaminsky your version with e2e is available on Store ? @rullzer the status of desktop ?

**Comment by tobiasKaminsky** [comment]
@marinofaggiana is your question somehow related to this issue? If not, please open up a new one.
(and yes, android is available as alpha version for registered test users)

**Comment by tobiasKaminsky** [comment]
As agreed we append the salt to the crypted key split by "|" encoded to base64 (same like on other)

**Comment by marinofaggiana** [comment]
ok, when apply this modify ?

**Comment by tobiasKaminsky** [comment]
I am doing it tomorrow, so it is in the next release.

**Comment by marinofaggiana** [comment]
@tobiasKaminsky  ping me when done on your server for test

**Comment by tobiasKaminsky** [comment]
@marinofaggiana I integrated in my server with user "tobi2" and password "tobi2".
In the root folder of this user is the 12 word password.

**Comment by marinofaggiana** [comment]
ok @tobiasKaminsky but the dir Enc is locked ?

**Comment by tobiasKaminsky** [comment]
Was this file uploaded by you?
I tried it and uploaded "tobi2-pass (2).txt" and it worked for me.

**Comment by marinofaggiana** [comment]
yes it's ok, was a old file in cache, all ok

**Comment by rullzer** [comment]
This is done also on the desktop client now

**Comment by rullzer** [comment]
We should update the RFC

**Comment by tobiasKaminsky** [comment]
Done in #11
