### ISSUE TITLE
IV for shared part should also be stored in the metadata

### ISSUE THREAD

**Issue by rullzer** [nextcloud/end_to_end_encryption_rfc#6]
Right now the sharing part of the metadata has no place to store the IV. So on android this is just appended again to the cipher text.

We should just store the IV in the metadata directly. So we have only 1 format.

**Comment by tobiasKaminsky** [comment]
IV is currently appended on android to encrypt/decrypt the private key.
I have no better idea where to place the IV as if we store it in the metadata it is related to the folder, which it is in fact not, but it is only related to the user.

**Comment by rullzer** [comment]
Ok lets just leave it appended. We can cleanup once we move stuff to a version 2 of the metadata.
